@APIs_HostAddress = http://localhost:6123

GET {{APIs_HostAddress}}/weatherforecast/
Accept: application/json
 
### Get all blog posts
GET {{APIs_HostAddress}}/api/blogpost
Accept: application/json 

### Get a specific blog post by ID
GET {{APIs_HostAddress}}/api/blogpost/1
Accept: application/json 

### Create a new blog post
POST {{APIs_HostAddress}}/api/blogpost
Content-Type: application/json
{
  "username": "newuser",
  "dateCreated": "2024-07-27T00:00:00Z",
  "text": "This is a new blog post."
} 

### Update an existing blog post by ID
PUT {{APIs_HostAddress}}/api/blogpost/1
Content-Type: application/json
{
  "id": 1,
  "username": "updateduser",
  "dateCreated": "2024-07-27T00:00:00Z",
  "text": "This blog post has been updated."
} 

### Delete a blog post by ID
DELETE {{APIs_HostAddress}}/api/blogpost/1

###

